### ISSUE TITLE
[Mapping Issue] Telecoms turrets are not connected to control panel

### ISSUE THREAD

**Issue by Tename** [Yawn-Wider/YWPolarisVore#643] opened 2020-03-08 04:49 UTC
#### Brief description of the issue
All turrets in Tcoms are not linked to the turret controls so can not be disabled.

#### What you expected to happen
Turret to go off

#### What actually happened
oh god oh fuck please stop shooting

#### Steps to reproduce
- Swipe ID on turret controls
- Turn off the turrets
- Walk inside
- Oh god oh fuck my leg.

#### Code Revision
Server revision: - 2020-03-07 

ed98aa3e756e4c0f952c411308d274c1d1e26b4d 
 
#### Anything else you may wish to add:
I saw an issue for this that appears to have been closed but it's still not fixed, and it was recently relevant.

**Comment by izac112** [comment] 2020-03-08 04:51
Issue is still open this is a duplicate of #333

**Closed** 2020-03-08 04:53 UTC

**Comment by Tename** [comment] 2020-03-08 04:56
Ah sorry, I only saw another one that was closed my bad.
