### ISSUE TITLE
Zaddat defibs

### ISSUE THREAD

**Issue by Sgtwok** [Yawn-Wider/YWPolarisVore#86] opened 2019-04-14 03:18 UTC
#### Brief overview of the feature

Allow Zaddat shrouds to be defibbable
#### What you want to happen
Allow zaddat to be defibrillated  through their shroud suits so they can actually be revived.

**Comment by Dwaggy** [comment] 2019-04-14 04:49
At a push, the CMO's defib should be able to revive them through the suit, so long as they're revivable at all even in that method.
But otherwise, yeah. this is likely something thats going to need looking in to, since i assume they can't be resleeved for similar reasons vox cant, what with the 'we cant breath/live in your atmos'.

**Comment by Hawk-v3** [comment] 2019-04-14 17:59
I figure this is most likely going to be an upstream issue, but I'll have a look. If it's fixable easily, I'll do it. If it requires big changes, it'll be on upstream.

**Comment by Hawk-v3** [comment] 2019-07-09 19:58
It seems looking upstream that this is intended of them, including them also taking more damage from most sources?

**Comment by Jonathan-Fort** [comment] 2019-07-12 03:15
Suggest, that if this is intended behavior, we marked this as "wont-fix"

**Closed** 2019-07-14 19:39 UTC
Labels: upstream, wontfix
